PRN221_VotingSystem/Pages/Admin/User/UserManager.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PRN221_VotingSystem.DAL;
using PRN221_VotingSystem.Models;

namespace PRN221_VotingSystem.Pages.Admin.User
{
    public class UserManagerModel : PageModel
    {
        public List<Account> Accounts { get; private set; }
        public UserManagerModel()
        {
            Accounts = new List<Account>();
        }
        public IActionResult OnGet()
        {
            var isAdmin = HttpContext.Session.GetString("IsAdmin");
            if (isAdmin != "true")
            {
                return RedirectToPage("/HomePage");
            }

            Accounts = AccountDAO.Instance.GetAllAccounts();
            return Page();
        }
        public void OnPostSearch(string userName)
        {
            var listAccount = AccountDAO.Instance.GetAllAccounts();
            Accounts = listAccount.Where(u => u.Username.Contains(userName)).ToList();
        }
        public void OnPostDelete(int userId)
        {
            var listAccount = AccountDAO.Instance.GetAllAccounts();
            var accountToBeDeleted = listAccount.FirstOrDefault(u => u.UserId == userId);
            try
            {
                using var data = new PRN221_DBContext();
                data.Accounts.Remove(accountToBeDeleted);
                data.SaveChanges();
                Accounts = AccountDAO.Instance.GetAllAccounts();
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }


    }
}

PRN221_VotingSystem/Pages/Admin/User/Manage.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "User Management";
}

<style>
    .full-height-container {
        height: 80vh !important;
    }
</style>

<div class="jumbotron text-center">
    <h1>User Management</h1>
</div>
<br>
<br>
<br>
<p class="card-text">Search User here</p>
<br>
<div class="container">
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Username</th>
                <th scope="col">Name</th>
                <th scope="col">Email</th>
                <th scope="col">Phone</th>
                <th scope="col">Address</th>
                <th scope="col">DOB</th>
                <th scope="col">Gender</th>
                <th scope="col">Job</th>
                <th scope="col">Select</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th scope="row">1</th>
                <td>admin</td>
                <td>Admin</td>
                <td>admin@example.com</td>
                <td>0123123123</td>
                <td>Hoa Lac</td>
                <td>1999-12-31</td>
                <td>Male</td>
                <td>Developer</td>
                <td></td>
            </tr>
            <tr>
                <th scope="row">2</th>
                <td>user1</td>
                <td>User1</td>
                <td>user1@example.com</td>
                <td>0123412341</td>
                <td>Ho Chi Minh</td>
                <td>2001-12-31</td>
                <td>Female</td>
                <td>Student</td>
                <td></td>
            </tr>
        </tbody>
    </table>
</div>

PRN221_VotingSystem/Pages/Admin/User/UserManager.cshtml
@page
@model PRN221_VotingSystem.Pages.Admin.User.UserManagerModel
@{
    ViewData["Title"] = "User Management";
}

<style>
    .full-height-container {
        height: 80vh !important;
    }
</style>

<div class="jumbotron text-center">
    <h1>User Management</h1>
</div>
<br>
<br>
<br>
<p class="card-text">Search User here</p>
<div>
    <form asp-page-handler="Search">
        <input name="userName" type="text"/>
        <button>Search</button>
    </form>
</div>
<br>
<div class="container">
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Username</th>
                <th scope="col">Name</th>
                <th scope="col">Email</th>
                <th scope="col">Phone</th>
                <th scope="col">Address</th>
                <th scope="col">DOB</th>
                <th scope="col">Gender</th>
                <th scope="col">Job</th>
                <th scope="col">Select</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var account in Model.Accounts)
            {
                <tr>
                    <th scope="row">@account.UserId</th>
                    <td>@account.Username</td>
                    <td>@account.FirstName @account.LastName</td>
                    <td>@account.Email</td>
                    <td>@account.Phone</td>
                    <td>@account.Address</td>
                    <td>@account.Dob.ToString("dd/MM/yyyy")</td>
                    <td>@account.Gender</td>
                    <td>@account.Job</td>
                    <td><form asp-page-handler="Delete"><input hidden name="userId" value="@account.UserId"/><button>Delele</button></form></td>
                </tr>
            }
        </tbody>
    </table>
</div>